services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    ports:
      - "5439:5432"  # A porta 5435 no seu host será mapeada para a porta 5432 no contêiner
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
